apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - external-secret.yaml

# Image name must match what's in deployment.yaml.
# Overlays override newName + newTag per environment.
images:
  - name: platform/saas-api-gateway
    newName: 194636597980.dkr.ecr.eu-central-1.amazonaws.com/platform/saas-api-gateway
    newTag: latest
